In [2]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter

plt.style.use("default")

Matplotlib is building the font cache; this may take a moment.

In [4]:
DATA_DIR = "data_2026_A2/data"


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


train_task1 = load_json(
    f"{DATA_DIR}/training_set_task1.txt"
)

dev_task1 = load_json(
    f"{DATA_DIR}/dev_set_task1.txt"
)

test_task1 = load_json(
    f"{DATA_DIR}/test_set_task1.txt"
)


train_task2 = load_json(
    f"{DATA_DIR}/training_set_task2.txt"
)

dev_task2 = load_json(
    f"{DATA_DIR}/dev_set_task2.txt"
)

test_task2 = load_json(
    f"{DATA_DIR}/test_set_task2.txt"
)


print("Task 1")
print("Train:", len(train_task1))
print("Dev:", len(dev_task1))
print("Test:", len(test_task1))


print("\nTask 2")
print("Train:", len(train_task2))
print("Dev:", len(dev_task2))
print("Test:", len(test_task2))

Task 1
Train: 688
Dev: 63
Test: 200

Task 2
Train: 688
Dev: 63
Test: 200

In [5]:
pd.DataFrame(train_task1).head()

,id,labels,text
0,128,[Black-and-white Fallacy/Dictatorship],THERE ARE ONLY TWO GENDERS\n\nFEMALE \n\nMALE\n
1,189,[],This is not an accident!
2,96,"[Loaded Language, Name calling/Labeling, Sloga...",SO BERNIE BROS HAVEN'T COMMITTED VIOLENCE EH?\...
3,154,"[Causal Oversimplification, Loaded Language, N...",PATHETIC\n\nThe Cowardly Asshole\nWeak Failure...
4,15,[],WHO TRUMP REPRESENTS\n\nWHO DEMOCRATS REPRESENT\n

In [6]:
pd.DataFrame(train_task2).head()

,id,text,labels
0,128,THERE ARE ONLY TWO GENDERS\n\nFEMALE \n\nMALE\n,"[{'start': 0, 'end': 41, 'technique': 'Black-a..."
1,189,This is not an accident!,[]
2,96,SO BERNIE BROS HAVEN'T COMMITTED VIOLENCE EH?\...,"[{'end': 83, 'start': 47, 'technique': 'Slogan..."
3,154,PATHETIC\n\nThe Cowardly Asshole\nWeak Failure...,"[{'end': 8, 'start': 0, 'technique': 'Loaded L..."
4,15,WHO TRUMP REPRESENTS\n\nWHO DEMOCRATS REPRESENT\n,[]

In [7]:
dataset_summary = pd.DataFrame(
    {
        "Split":
        [
            "Train",
            "Validation",
            "Test"
        ],

        "Task 1":
        [
            len(train_task1),
            len(dev_task1),
            len(test_task1)
        ],

        "Task 2":
        [
            len(train_task2),
            len(dev_task2),
            len(test_task2)
        ]
    }
)


display(dataset_summary)

        Split  Task 1  Task 2
0       Train     688     688
1  Validation      63      63
2        Test     200     200

In [8]:
train_df = pd.DataFrame(train_task1)


train_df["text_length"] = (
    train_df["text"]
    .apply(
        lambda x: len(x.split())
    )
)


train_df["character_length"] = (
    train_df["text"]
    .apply(len)
)


train_df[
    [
        "text_length",
        "character_length"
    ]
].describe()

       text_length  character_length
count   688.000000        688.000000
mean     17.962209        103.741279
std      11.572631         67.788071
min       1.000000          5.000000
25%      10.000000         54.000000
50%      15.000000         86.000000
75%      24.000000        142.000000
max      72.000000        427.000000